apiVersion: v1
kind: Service
metadata:
  name: go-hello-world-service
  namespace: default
  labels:
    app: go-hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: go-hello-world
---
apiVersion: v1
kind: Service
metadata:
  name: go-hello-world-nodeport
  namespace: default
  labels:
    app: go-hello-world
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: go-hello-world