name: AWS Connection Test

on:
  # 수동으로 실행할 수 있게 설정
  workflow_dispatch:

jobs:
  test-aws-connection:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::727158410149:role/sm-role
          aws-region: us-east-2
          
      - name: Test AWS Connection
        run: |
          # AWS 인증 테스트
          aws sts get-caller-identity
          
          # 명시적으로 성공 표시
          echo "AWS connection successful!"